default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: grace_page_development

  
test:
  <<: *default
  database: grace_page_test


production:
  <<: *default
  database: grace_page_production
